runtime: python311

env: standard

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
