version: '3.8'

services:
  trading-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_APP=app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
